### ISSUE TITLE
Local Generation Failing on Hash Check

### ISSUE THREAD

**Issue by MT-Fun** [sotnrando/sotnrando#64]
New issues must complete all sections of this template or they will be
automatically closed.

Use this template if your bug does not relate to a seed being completable due
to relic placement.

# Seed Information
All Seeds

# Randomizer version:
3.5.9

# Operating system and version:
Windows 10
Version 20H2 (OS Build 19042.928)

# Browser and version:
Running Locally, Powershell v.5.1.19

# Emulator and version:
Not getting that far.

# Bug description
PS F:\Repos\Rando> node randomize -p safe -vvv
Seed:  1619559439939
TypeError: Cannot read property 'subtle' of undefined
    at sha256 (F:\Repos\Rando\src\util.js:32:19)
    at checked.sum (F:\Repos\Rando\src\util.js:672:12)
    at randomize (F:\Repos\Rando\randomize:944:33)
    at Object.<anonymous> (F:\Repos\Rando\randomize:1079:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

The same error happens when I put my Bin file as an input, or when I specify a ppf file as an output.

# How to reproduce:
Running the command locally.  Not sure if I'm missing a prerequisite that's needed to run the Hash check locally.

**Comment by 3snowp7im** [comment]
Upgrade your node installation to at least 15.x
