### ISSUE TITLE
Unhandled Promise Rejection?

### ISSUE THREAD

**Issue by MainMemory** [sotnrando/sotnrando#67]
I've been using the randomizer locally, and for a while now it's been failing with the same error every time I try to run it:
```
>git reset --hard
>git pull
>npm install
>node randomize -vvvv  -i "D:\CD\PS1\Castlevania - Symphony of the Night (Track 1).bin" -o D:\CD\PS1\SOTNR.bin -p Adventure
(node:14132) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subtle' of undefined
    at sha256 (D:\Documents\GitHub\SotN-Randomizer\src\util.js:32:19)
    at checked.sum (D:\Documents\GitHub\SotN-Randomizer\src\util.js:672:12)
    at randomize (D:\Documents\GitHub\SotN-Randomizer\randomize:1015:30)
```

**Comment by 3snowp7im** [comment]
Upgrade to at least node 15x
